package org.paulvargas.joker.ejb;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import javax.annotation.PostConstruct;
import javax.ejb.Singleton;
import javax.ejb.Startup;

@Singleton
@Startup
public class CountryEJB {

	private Map<String, String> countryMap;

	@PostConstruct
	private void init() {
		Map<String, String> map = new HashMap<>();
		map.put("AD", "Andorra");
		map.put("AE", "United Arab Emirates");
		map.put("AF", "Afghanistan");
		map.put("AG", "Antigua and Barbuda");
		map.put("AI", "Anguilla");
		map.put("AL", "Albania");
		map.put("AM", "Armenia");
		map.put("AO", "Angola");
		map.put("AQ", "Antarctica");
		map.put("AR", "Argentina");
		map.put("AS", "American Samoa");
		map.put("AT", "Austria");
		map.put("AU", "Australia");
		map.put("AW", "Aruba");
		map.put("AX", "Åland Islands");
		map.put("AZ", "Azerbaijan");
		map.put("BA", "Bosnia and Herzegovina");
		map.put("BB", "Barbados");
		map.put("BD", "Bangladesh");
		map.put("BE", "Belgium");
		map.put("BF", "Burkina Faso");
		map.put("BG", "Bulgaria");
		map.put("BH", "Bahrain");
		map.put("BI", "Burundi");
		map.put("BJ", "Benin");
		map.put("BL", "Saint Barthélemy");
		map.put("BM", "Bermuda");
		map.put("BN", "Brunei Darussalam");
		map.put("BO", "Bolivia (Plurinational State of)");
		map.put("BQ", "Bonaire, Sint Eustatius and Saba");
		map.put("BR", "Brazil");
		map.put("BS", "Bahamas");
		map.put("BT", "Bhutan");
		map.put("BV", "Bouvet Island");
		map.put("BW", "Botswana");
		map.put("BY", "Belarus");
		map.put("BZ", "Belize");
		map.put("CA", "Canada");
		map.put("CC", "Cocos (Keeling) Islands");
		map.put("CD", "Congo (Democratic Republic of the)");
		map.put("CF", "Central African Republic");
		map.put("CG", "Congo");
		map.put("CH", "Switzerland");
		map.put("CI", "Côte d'Ivoire");
		map.put("CK", "Cook Islands");
		map.put("CL", "Chile");
		map.put("CM", "Cameroon");
		map.put("CN", "China");
		map.put("CO", "Colombia");
		map.put("CR", "Costa Rica");
		map.put("CU", "Cuba");
		map.put("CV", "Cabo Verde");
		map.put("CW", "Curaçao");
		map.put("CX", "Christmas Island");
		map.put("CY", "Cyprus");
		map.put("CZ", "Czech Republic");
		map.put("DE", "Germany");
		map.put("DJ", "Djibouti");
		map.put("DK", "Denmark");
		map.put("DM", "Dominica");
		map.put("DO", "Dominican Republic");
		map.put("DZ", "Algeria");
		map.put("EC", "Ecuador");
		map.put("EE", "Estonia");
		map.put("EG", "Egypt");
		map.put("EH", "Western Sahara");
		map.put("ER", "Eritrea");
		map.put("ES", "Spain");
		map.put("ET", "Ethiopia");
		map.put("FI", "Finland");
		map.put("FJ", "Fiji");
		map.put("FK", "Falkland Islands (Malvinas)");
		map.put("FM", "Micronesia (Federated States of)");
		map.put("FO", "Faroe Islands");
		map.put("FR", "France");
		map.put("GA", "Gabon");
		map.put("GB", "United Kingdom of Great Britain and Northern Ireland");
		map.put("GD", "Grenada");
		map.put("GE", "Georgia");
		map.put("GF", "French Guiana");
		map.put("GG", "Guernsey");
		map.put("GH", "Ghana");
		map.put("GI", "Gibraltar");
		map.put("GL", "Greenland");
		map.put("GM", "Gambia");
		map.put("GN", "Guinea");
		map.put("GP", "Guadeloupe");
		map.put("GQ", "Equatorial Guinea");
		map.put("GR", "Greece");
		map.put("GS", "South Georgia and the South Sandwich Islands");
		map.put("GT", "Guatemala");
		map.put("GU", "Guam");
		map.put("GW", "Guinea-Bissau");
		map.put("GY", "Guyana");
		map.put("HK", "Hong Kong");
		map.put("HM", "Heard Island and McDonald Islands");
		map.put("HN", "Honduras");
		map.put("HR", "Croatia");
		map.put("HT", "Haiti");
		map.put("HU", "Hungary");
		map.put("ID", "Indonesia");
		map.put("IE", "Ireland");
		map.put("IL", "Israel");
		map.put("IM", "Isle of Man");
		map.put("IN", "India");
		map.put("IO", "British Indian Ocean Territory");
		map.put("IQ", "Iraq");
		map.put("IR", "Iran (Islamic Republic of)");
		map.put("IS", "Iceland");
		map.put("IT", "Italy");
		map.put("JE", "Jersey");
		map.put("JM", "Jamaica");
		map.put("JO", "Jordan");
		map.put("JP", "Japan");
		map.put("KE", "Kenya");
		map.put("KG", "Kyrgyzstan");
		map.put("KH", "Cambodia");
		map.put("KI", "Kiribati");
		map.put("KM", "Comoros");
		map.put("KN", "Saint Kitts and Nevis");
		map.put("KP", "Korea (Democratic People's Republic of)");
		map.put("KR", "Korea (Republic of)");
		map.put("KW", "Kuwait");
		map.put("KY", "Cayman Islands");
		map.put("KZ", "Kazakhstan");
		map.put("LA", "Lao People's Democratic Republic");
		map.put("LB", "Lebanon");
		map.put("LC", "Saint Lucia");
		map.put("LI", "Liechtenstein");
		map.put("LK", "Sri Lanka");
		map.put("LR", "Liberia");
		map.put("LS", "Lesotho");
		map.put("LT", "Lithuania");
		map.put("LU", "Luxembourg");
		map.put("LV", "Latvia");
		map.put("LY", "Libya");
		map.put("MA", "Morocco");
		map.put("MC", "Monaco");
		map.put("MD", "Moldova (Republic of)");
		map.put("ME", "Montenegro");
		map.put("MF", "Saint Martin (French part)");
		map.put("MG", "Madagascar");
		map.put("MH", "Marshall Islands");
		map.put("MK", "Macedonia (the former Yugoslav Republic of)");
		map.put("ML", "Mali");
		map.put("MM", "Myanmar");
		map.put("MN", "Mongolia");
		map.put("MO", "Macao");
		map.put("MP", "Northern Mariana Islands");
		map.put("MQ", "Martinique");
		map.put("MR", "Mauritania");
		map.put("MS", "Montserrat");
		map.put("MT", "Malta");
		map.put("MU", "Mauritius");
		map.put("MV", "Maldives");
		map.put("MW", "Malawi");
		map.put("MX", "Mexico");
		map.put("MY", "Malaysia");
		map.put("MZ", "Mozambique");
		map.put("NA", "Namibia");
		map.put("NC", "New Caledonia");
		map.put("NE", "Niger");
		map.put("NF", "Norfolk Island");
		map.put("NG", "Nigeria");
		map.put("NI", "Nicaragua");
		map.put("NL", "Netherlands");
		map.put("NO", "Norway");
		map.put("NP", "Nepal");
		map.put("NR", "Nauru");
		map.put("NU", "Niue");
		map.put("NZ", "New Zealand");
		map.put("OM", "Oman");
		map.put("PA", "Panama");
		map.put("PE", "Peru");
		map.put("PF", "French Polynesia");
		map.put("PG", "Papua New Guinea");
		map.put("PH", "Philippines");
		map.put("PK", "Pakistan");
		map.put("PL", "Poland");
		map.put("PM", "Saint Pierre and Miquelon");
		map.put("PN", "Pitcairn");
		map.put("PR", "Puerto Rico");
		map.put("PS", "Palestine, State of");
		map.put("PT", "Portugal");
		map.put("PW", "Palau");
		map.put("PY", "Paraguay");
		map.put("QA", "Qatar");
		map.put("RE", "Réunion");
		map.put("RO", "Romania");
		map.put("RS", "Serbia");
		map.put("RU", "Russian Federation");
		map.put("RW", "Rwanda");
		map.put("SA", "Saudi Arabia");
		map.put("SB", "Solomon Islands");
		map.put("SC", "Seychelles");
		map.put("SD", "Sudan");
		map.put("SE", "Sweden");
		map.put("SG", "Singapore");
		map.put("SH", "Saint Helena, Ascension and Tristan da Cunha");
		map.put("SI", "Slovenia");
		map.put("SJ", "Svalbard and Jan Mayen");
		map.put("SK", "Slovakia");
		map.put("SL", "Sierra Leone");
		map.put("SM", "San Marino");
		map.put("SN", "Senegal");
		map.put("SO", "Somalia");
		map.put("SR", "Suriname");
		map.put("SS", "South Sudan");
		map.put("ST", "Sao Tome and Principe");
		map.put("SV", "El Salvador");
		map.put("SX", "Sint Maarten (Dutch part)");
		map.put("SY", "Syrian Arab Republic");
		map.put("SZ", "Swaziland");
		map.put("TC", "Turks and Caicos Islands");
		map.put("TD", "Chad");
		map.put("TF", "French Southern Territories");
		map.put("TG", "Togo");
		map.put("TH", "Thailand");
		map.put("TJ", "Tajikistan");
		map.put("TK", "Tokelau");
		map.put("TL", "Timor-Leste");
		map.put("TM", "Turkmenistan");
		map.put("TN", "Tunisia");
		map.put("TO", "Tonga");
		map.put("TR", "Turkey");
		map.put("TT", "Trinidad and Tobago");
		map.put("TV", "Tuvalu");
		map.put("TW", "Taiwan, Province of China");
		map.put("TZ", "Tanzania, United Republic of");
		map.put("UA", "Ukraine");
		map.put("UG", "Uganda");
		map.put("UM", "United States Minor Outlying Islands");
		map.put("US", "United States of America");
		map.put("UY", "Uruguay");
		map.put("UZ", "Uzbekistan");
		map.put("VA", "Holy See");
		map.put("VC", "Saint Vincent and the Grenadines");
		map.put("VE", "Venezuela (Bolivarian Republic of)");
		map.put("VG", "Virgin Islands (British)");
		map.put("VI", "Virgin Islands (U.S.)");
		map.put("VN", "Viet Nam");
		map.put("VU", "Vanuatu");
		map.put("WF", "Wallis and Futuna");
		map.put("WS", "Samoa");
		map.put("YE", "Yemen");
		map.put("YT", "Mayotte");
		map.put("ZA", "South Africa");
		map.put("ZM", "Zambia");
		map.put("ZW", "Zimbabwe");
		countryMap = Collections.unmodifiableMap(map);
	}
	
	public String getCountry(String code) {
		return countryMap.get(code);
	}

}
